site_name: Data Leak Inspector

repo_name: Smithech/data-leak-inspector
repo_url: https://github.com/Smithech/data-leak-inspector

strict: false

theme:
  name: material

  logo: assets/logo.png
  favicon: assets/favicon.png

  icon:
    repo: fontawesome/brands/github

  palette:
  - scheme: default
    primary: blue
    accent: indigo
    toggle:
      icon: material/weather-night
      name: Cambiar a modo oscuro

  - scheme: slate
    primary: blue
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: Cambiar a modo claro

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.footer

    - search.highlight
    - search.suggest
    - search.share

    - content.code.copy
    - content.code.annotate

    - toc.follow
    - toc.integrate

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/Smithech
        name: GitHub

      - icon: fontawesome/brands/python
        link: https://pypi.org/project/data-leak-inspector/
        name: PyPI

      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/johansmithrueda/
        name: LinkedIn  
  
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

  - pymdownx.tabbed:
      alternate_style: true

  - toc:
      permalink: true

plugins:
  - search

  - awesome-pages

  - i18n:
      docs_structure: folder

      reconfigure_material: true

      fallback_to_default: true

      languages:

        - locale: es
          default: true
          name: Español
          build: true

          nav:
            - Inicio: index.md 
            - Comandos: 
              - comandos/auth.md
              - comandos/init.md
              - comandos/logout.md
              - comandos/scan.md
            - Tutoriales: tutoriales/overview.md 
            - FAQ: faq.md
            - Privacidad: privacidad.md
            - Changelog: changelog.md

        - locale: en
          name: English
          build: true

          nav:
            - Home: index.md
            - Commands: 
              - comandos/auth.md
              - comandos/init.md
              - comandos/logout.md
              - comandos/scan.md
            - Tutorials: tutorials/overview.md  
            - FAQ: faq.md
            - Privacy: privacy.md
            - Changelog: changelog.md